### ISSUE TITLE
KeyError: 'bboxes'  KeyError: Caught KeyError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by HXB-1997** [anshulpaigwar/Frustum-Pointpillars#9]
when I am training model, when it comes to #EVAL   :

 File "/home/whut-4/anaconda3/envs/ZC2_pointpillars/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/whut-4/anaconda3/envs/ZC2_pointpillars/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/whut-4/anaconda3/envs/ZC2_pointpillars/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/whut-4/anaconda3/envs/ZC2_pointpillars/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/whut-4/Desktop/HXB/F_Pointpillar/05-13/Frustum-Pointpillars/second/pytorch/builder/input_reader_builder.py", line 42, in __getitem__
    return self._dataset[idx]
  File "/home/whut-4/Desktop/HXB/F_Pointpillar/05-13/Frustum-Pointpillars/second/data/dataset.py", line 68, in __getitem__
    prep_func=self._prep_func)
  File "/home/whut-4/Desktop/HXB/F_Pointpillar/05-13/Frustum-Pointpillars/second/data/preprocess.py", line 566, in _read_and_prep_v9
    example = prep_func(input_dict=input_dict)
  File "/home/whut-4/Desktop/HXB/F_Pointpillar/05-13/Frustum-Pointpillars/second/data/preprocess.py", line 150, in prep_pointcloud
    ref_bboxes = input_dict["bboxes"]
KeyError: 'bboxes'

**Comment by yishiyishiyishiyi** [comment]
Hello! Did you solve this problem? I encountered the same error and I do not know what to do

**Comment by HXB-1997** [comment]
> Hello! Did you solve this problem? I encountered the same error and I do not know what to do

https://github.com/anshulpaigwar/Frustum-Pointpillars/issues/10 this works
